ci: adds `check-japanese` job (#265)
* ci: adds `check-japanese` job

* exclude nightly x check-japanese

* allow(check-japanese)

* removes Japanese from scenario test (needs to change test expectation over `ORDER BY name`)

* fix: check-japanese task to sucessfully exit even when no line matches

* rm all Japanese

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -87,6 +87,21 @@ git ls-files |grep -E '.rs$' |(! xargs grep 'unimplemented!')
 git ls-files |grep -E '.rs$' |(! xargs grep 'todo!')
 ''']
 
+[tasks.check-japanese]
+script = ['''
+#!/usr/bin/env bash -eux
+f=$(mktemp)
+git ls-files |xargs perl -Mutf8 -CSD -wnle '/[\p{Han}\p{Hiragana}\p{Katakana}]/ and print;' |( grep -v 'allow(check-japanese)' > $f || : )
+
+if [ $(cat $f |wc -l) -eq 0 ]; then
+  true
+else
+  cat $f
+  echo 'ERROR: Some files include Japanese text. To welcome contribution from all over the world, we decided to use only English 💪'
+  false
+fi
+''']
+
 [tasks.check-trash]
 script = ['''
 #!/usr/bin/env bash -eux
